# .streamlit/config.toml

[theme]
# צבע ראשי - ישמש לכפתורים, אלמנטים אינטראקטיביים וכו'.
# גוון תכלת-טורקיז מרגיע ומקצועי
primaryColor = "#5D9C93" # היה #4A90E2 כחול, שונה לגוון ירקרק מרגיע

# צבע רקע ראשי של האפליקציה
# גוון אוף-ווייט / אפור בהיר מאוד, נעים לעין
backgroundColor = "#F8F9FA" # היה #F0F2F6 אפרפר, שונה לגוון בהיר יותר

# צבע רקע משני - ישמש לרקעים של קונטיינרים, סרגל צד (אם יש) וכו'.
# גוון אפור מעט יותר כהה מהרקע הראשי, ליצירת הפרדה עדינה
secondaryBackgroundColor = "#E9ECEF" # היה #FFFFFF לבן, שונה לאפור בהיר

# צבע טקסט ראשי
# אפור כהה מאוד, לקריאות טובה
textColor = "#212529" # היה #262730, שונה לגוון סטנדרטי יותר

# פונט - אפשר לבחור מבין "serif", "sans serif", "monospace"
# "sans serif" הוא בדרך כלל הבחירה המודרנית והקריאה ביותר לממשקים
font = "sans serif"

[server]
# מאפשר ל-Streamlit לזהות שינויים בקבצים ולטעון מחדש אוטומטית
# שימושי בזמן פיתוח
runOnSave = true

[logger]
# רמת הלוגים שיוצגו במסוף (debug, info, warning, error, critical)
level = "info"

[runner]
# מאפשר ל-Streamlit להשתמש ב-watchdog כדי לזהות שינויים בקבצים בצורה יעילה יותר
# במערכות מסוימות זה יכול לשפר את מהירות הטעינה מחדש
fastReruns = true
